#!/usr/bin/env python

class Matriz:

    def __init__(self, filas, columnas, aleatoria=False):
        self.filas = filas
        self.columnas = columnas
        self.matriz = []
        
        if aleatoria:
            temp1 = []
            for i in range(0, self.filas):
                temp2 = []
                for j in range(0, self.columnas):
                    
                    temp2.append(random.randint(0, 9))
                temp1.append(temp2)            
            self.matriz = temp1

        else:
            temp1 = []
            for i in range(0, self.filas):
                temp2 = []
                for j in range(0, self.columnas):
                    
                    temp2.append(0)
                temp1.append(temp2)            
            self.matriz = temp1
            
    def imprimir(self):
        for i in range(len(self.matriz)):
            temp = self.matriz[i]
            print(f"{temp}", end="")

            print("")
            
    def sumar(self, otra):
        nueva_matriz = []
        if self.filas == otra.filas and self.columnas == otra.columnas:
            for i in range(0,self.filas):
                for k in range(0,self.columnas):
                    nuevo_elemento = i + k
                    print("fila: ", i)
                    print("columna: ", k)
    
    def restar(self,otra):
        print(otra)

    def multiplicar(self, otra) :
        print(otra)


import random
if __name__ == "__main__":
    matriz_1 = Matriz(3,5)
    matriz_1.imprimir()
    print("")
    matriz_1 = Matriz(3,5, True)
    matriz_1.imprimir()


    # matriz_2 = Matriz(2,2,True)
    #matriz_1.imprimir()
    # matriz_1.sumar(matriz_2)


